---
# tasks file for apache-vhosts-role

- name: Install Apache Web Server
  yum:
      name: httpd # not required. A package name or package specifier with version, like C(name-1.0).,If a previous version is specified, the task also needs to turn C(allow_downgrade) on. See the C(allow_downgrade) documentation for caveats with downgrading packages.,When using state=latest, this can be C('*') which means run C(yum -y update).,You can also pass a url or a local path to a rpm file (using state=present). To operate on several packages this can accept a comma separated list of packages or (as of 2.0) a list of packages.
      state: latest # not required. choices: absent;installed;latest;present;removed. Whether to install (C(present) or C(installed), C(latest)), or remove (C(absent) or C(removed)) a package.,C(present) and C(installed) will simply ensure that a desired package is installed.,C(latest) will update the specified package if it's not of the latest available version.,C(absent) and C(removed) will remove the specified package.
  become: true

- name: Start and enable Apache Web Service
  service:
      name: httpd # required. Name of the service.
      enabled: true # not required. Whether the service should start on boot. B(At least one of state and enabled are required.)
      state: started # not required. choices: reloaded;restarted;started;stopped. C(started)/C(stopped) are idempotent actions that will not run commands unless necessary.  C(restarted) will always bounce the service.  C(reloaded) will always reload. B(At least one of state and enabled are required.) Note that reloaded will start the service if it is not already started, even if your chosen init system wouldn't normally.
  become: true
  
- name: Configure virtual hosts
  template:
    src: vhost-config-template.j2
    dest: /etc/httpd/conf.d/{{ item.vhost_domain }}-vhost.conf
  loop: "{{ vhosts }}"
  notify: restart_httpd
  become: true
  
- name: Create virtual Host Document Root {{ vhost_dir }}
  file:
    path: "{{ item.vhost_dir }}/{{ item.vhost_domain }}/"
    state: directory
  loop: "{{ vhosts }}"
  become: true
  
- name: Place Temporary Home Page
  file:
    path: "{{ item.vhost_dir }}/{{ item.vhost_domain }}/index.html"
    state: touch
  loop: "{{ vhosts }}"
  become: true
  
- name: Add home page contents by template
  template:
    src: vhost-index-template.j2
    dest: "{{ item.vhost_dir }}/{{ item.vhost_domain }}/index.html"
  loop: "{{ vhosts }}"
  become: true
  